<?php namespace Taco\HCF\other\entities;

use pocketmine\entity\animation\DeathAnimation;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Location;
use pocketmine\entity\Villager;
use pocketmine\event\entity\EntityDamageByEntityEvent;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\item\Item;
use pocketmine\nbt\NBT;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\DoubleTag;
use pocketmine\nbt\tag\FloatTag;
use pocketmine\nbt\tag\IntTag;
use pocketmine\nbt\tag\ListTag;
use pocketmine\nbt\tag\StringTag;
use pocketmine\nbt\TreeRoot;
use pocketmine\player\Player;
use pocketmine\world\generator\populator\Tree;
use Taco\HCF\Main;
use function var_dump;

class LogoutVillager extends Villager {

    private string $playerName = "";

    private int $time = 0;

    private int $tickk = 0;

    private array $items = [];

    public function __construct(Location $level, ?CompoundTag $nbt, string $playerName = "", array $items = []) {
        if ($playerName == "") return;
        parent::__construct($level, $nbt);
        $this->items = $items;
        $this->setMaxHealth(200);
        $this->setHealth(200);
        $this->playerName = $playerName;
        $this->time = 120;
        $this->setNameTagAlwaysVisible(true);
        $this->setNameTagVisible(true);
    }
private bool $isDed = false;
	public function attack(EntityDamageEvent $source) : void {
		if ($source instanceof EntityDamageByEntityEvent) {
			$dmg = $source->getDamager();
			if ($dmg instanceof Player) {
				if ($this->getHealth() - $source->getFinalDamage() > 0.1) {
					parent::attack($source);
					return;
				}
				$this->broadcastAnimation(new DeathAnimation($this));
				$player = Main::getInstance()->getServer()->getOfflinePlayerData($this->playerName);
				$items = $this->items;
				$drops = [];
				foreach ($items as $i) {
					$drops[] = $i;
				}
				Main::getInstance()->players[$dmg->getName()]["kills"] += 1;
				$player->setTag("Inventory", new ListTag([], NBT::TAG_Compound));
				Main::getInstance()->players[$this->playerName]["didDie"] = true;
				Main::getInstance()->getServer()->saveOfflinePlayerData($this->playerName, $player);
				Main::getInstance()->getServer()->broadcastMessage("§c" . $this->playerName . "§4[" . Main::getInstance()->players[$this->playerName]["kills"] . "] §r§7(Logger) §r§ewas killed by §c" . $dmg->getName()."§4[".Main::getInstance()->players[$dmg->getName()]["kills"]."] §r§eusing §r".($dmg->getInventory()->getItemInHand()->getCustomName() == "" ? $dmg->getInventory()->getItemInHand()->getName() : $dmg->getInventory()->getItemInHand()->getCustomName()));
				foreach ($drops as $drop) {
					if (count($drops) < 1) break;
					$this->getPosition()->getWorld()->dropItem($this->getPosition(), $drop);
				}
				$this->isDed = true;

			}
		} else {
			$source->cancel();
		}
	}
    public function entityBaseTick(int $tickDiff = 1) : bool {
		parent::entityBaseTick($tickDiff);
        $this->tickk++;
        if (($this->tickk % 20) == 0) {
            if ((!$this->isAlive()) and (!$this->closed)) {
                $this->flagForDespawn();
                return false;
            }
            if (Main::getInstance()->getServer()->getPlayerByPrefix($this->playerName) !== null) {
                $this->flagForDespawn();
                return false;
            }
            $this->time--;
            $this->setNameTag("§f" . $this->playerName . " §e[§c" . Main::getUtils()->secondsToEnderpearlCD($this->time) . "§r§e] §c" . floor($this->getHealth()) . "§f/§c" . floor($this->getMaxHealth()));
            $this->isDed = true;
        }
		if ($this->isClosed() or $this->closed or !$this->isAlive() or $this->isDed) {
			$this->flagForDespawn();
		}
        return true;
    }

    public function tryChangeMovement(): void
	{
		parent::tryChangeMovement(); // TODO: Change the autogenerated stub
	}

	protected function getInitialSizeInfo() : EntitySizeInfo {
		return new EntitySizeInfo(1.5, 1.5);
	}

	protected function onDispose() : void{}

	public function saveNBT(): CompoundTag
	{
		return CompoundTag::create()->setByte("bruhhhhIHatePM4Entities", 1);
	}

	public function onRandomUpdate(): void
	{

	}









}